server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      max: ${HTTP_MAX_THREADS:100}
      max-queue-capacity: ${HTTP_MAX_QUEUE:300}

logging:
  config: "classpath:logback-spring.xml"

spring:
  application:
    name: tweet-save-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    listener:
      missing-topics-fatal: true
    topics:
      tweet-api:
        save:
          topic: ${KAFKA_TWEET_SAVE_TOPIC:tweet.save}
          group: ${KAFKA_TWEET_SAVE_GROUP:tweet-save-service}
          enabled: ${KAFKA_TWEET_SAVE_IS_ENABLED:true}
  elasticsearch:
    uris: ${ELASTIC_URL:localhost:9200}
    username: ${ELASTIC_USERNAME:}
    password: ${ELASTIC_PASSWORD:}
    connection-timeout: ${ELASTIC_CONNECTION_TIMEOUT:PT3S}

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  server:
    port: ${MANAGEMENT_SERVER_PORT:88}
